__author__= "barun"
__date__  = "$20 May, 2011 12:19:00 PM$"

'''
Declares events and constants representing field positions in a trace file
generated by ns2.
'''

# Different events and their symbolic representations in a trace file
EVENT_SEND      = 's'
EVENT_RECEIVE   = 'r'
EVENT_DROP      = 'd'
EVENT_FORWARD   = 'f'

NS_EVENT_TYPE = {
    EVENT_SEND:     'Send',
    EVENT_RECEIVE:  'Receive',
    EVENT_DROP:     'Drop',
    EVENT_FORWARD:  'Forward',
}

NS_EVENTS = (EVENT_SEND, EVENT_RECEIVE, EVENT_DROP, EVENT_FORWARD, )

#Tokens
S_CUR_NODE_ID_TOKEN = '-Hs'
S_NXT_NODE_ID_TOKEN = '-Hd'
S_TRACE_LEVEL_TOKEN = '-Nl'
S_FLOW_ID_TOKEN     = '-If'
S_SEQ_NUM_TOKEN     = '-Ii'
S_SRC_FIELD_TOKEN   = '-Is'
S_DST_FIELD_TOKEN   = '-Id'
S_PKT_TYPE_TOKEN    = '-It'
S_PKT_LEN_TOKEN     = '-Il'

# Field positions
I_EVENT             = 0
I_TIMESTAMP_TOKEN   = 1
I_TIMESTAMP         = 2
I_CUR_NODE_ID_TOKEN = 3
I_CUR_NODE_ID       = 4
I_NXT_NODE_ID_TOKEN = 5
I_NXT_NODE_ID       = 6
I_TRACE_LEVEL_TOKEN = 17
I_TRACE_LEVEL       = 18
I_SRC_FIELD_TOKEN   = 29
I_SRC_ADDR_PORT     = 30    # Combined together: addr.port
I_DST_FIELD_TOKEN   = 31
I_DST_ADDR_PORT     = 32    # Combined together: addr.port
I_PKT_TYPE_TOKEN    = 33
I_PKT_TYPE          = 34
I_PKT_LEN_TOKEN     = 35
I_PKT_LEN           = 36
I_FLOW_ID_TOKEN     = 37
I_FLOW_ID           = 38
I_SEQ_NUM_TOKEN     = 39
I_SEQ_NUM           = 40

# Trace levels -- from where an event has been logged
L_AGENT     = 'AGT'
L_ROUTER    = 'RTR'
L_MAC       = 'MAC'
L_QUEUE     = 'IFQ'